{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-secret
type: Opaque
stringData:
  {{- if eq .Values.auth.tunnelToken  "" }}
  tunnel-config.json: >
    {
      "AccountTag": "{{ required "The Argo Tunnel Account Tag is missing." .Values.auth.accountTag }}",
      "TunnelSecret": "{{ required "The Argo Tunnel Secret is missing." .Values.auth.tunnelSecret }}",
      "TunnelID": "{{ required "The Argo Tunnel ID is missing." .Values.tunnelID }}",
      "TunnelName": "{{ required "The Argo Tunnel Name is missing." .Values.auth.tunnelName }}"
    }
  {{ else }}
  token: {{ .Values.auth.tunnelToken }}
  {{- end }}
{{- end }}
